import unittest
import os
from pynta.geometricanalysis import *

class UtilsTest(unittest.TestCase):

    def test_validate_TSs(self):
        fpath = os.path.abspath(os.path.dirname(__file__))
        path = os.path.join(os.path.split(fpath)[0],"pynta/testing_data/Ru0001_fischer_tropsch_3_17_25")
        metal = "Ru"
        facet = "hcp0001" 
        slab = read(os.path.join(path,"slab.xyz"))
        cas = SlabAdsorptionSites(slab, facet,allow_6fold=False,composition_effect=False,
                                    label_sites=True,
                                    surrogate_metal=metal)
        sites = cas.get_sites()
        site_adjacency = cas.get_neighbor_site_list()
        nslab = len(slab)
        
        TS_validity_info = {
            "TS0": {'7': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': []},
                        '4': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': True,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.6054655655874224],
                        'Fixed_Bond_Freq_Alignments': []},
                        '12': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': []}},
            "TS1": {'16': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': True,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': [0.0004011191923396565]},
                        '15': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': [0.02641687927751324]}},
            "TS2": {'32': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.8473309424384454],
                        'Fixed_Bond_Freq_Alignments': []},
                        '11': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.8218665842173611],
                        'Fixed_Bond_Freq_Alignments': []},
                        '43': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.8234500929569966],
                        'Fixed_Bond_Freq_Alignments': []},
                        '30': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.7688821381186464],
                        'Fixed_Bond_Freq_Alignments': []},
                        '24': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': True,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.8067875444858257],
                        'Fixed_Bond_Freq_Alignments': []}},
            "TS3": {'7': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.2484202179981068],
                        'Fixed_Bond_Freq_Alignments': []},
                        '17': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3796370901292356],
                        'Fixed_Bond_Freq_Alignments': []},
                        '8': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3548122556612303],
                        'Fixed_Bond_Freq_Alignments': []},
                        '21': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3698630271814236],
                        'Fixed_Bond_Freq_Alignments': []},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.2477085030996564],
                        'Fixed_Bond_Freq_Alignments': []}},
            "TS4": {'42': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.4554481860192272],
                        'Fixed_Bond_Freq_Alignments': [0.12136624398406007, 0.09561929043013818]},
                        '43': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': False,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [1.4257954665625219],
                        'Fixed_Bond_Freq_Alignments': [0.14269965286488415]},
                        '3': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.4590543117857138],
                        'Fixed_Bond_Freq_Alignments': [0.11833677641318387, 0.030997114172687728]},
                        '25': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.470616000880534],
                        'Fixed_Bond_Freq_Alignments': [0.1207371992866134, 0.03249574605521225]}},
            "TS5": {'72': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.421390166953647],
                        'Fixed_Bond_Freq_Alignments': [0.015783428455632034, 0.00840738433202082]},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.1741071180394884],
                        'Fixed_Bond_Freq_Alignments': [0.011518741599512008, 0.007804679966367412]}},
            "TS6": {'26': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.4142967571020177],
                        'Fixed_Bond_Freq_Alignments': []},
                        '43': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3884285183096006],
                        'Fixed_Bond_Freq_Alignments': []},
                        '24': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.409901667686973],
                        'Fixed_Bond_Freq_Alignments': []},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3915426547240624],
                        'Fixed_Bond_Freq_Alignments': []}},
            "TS7": {'35': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.1804322145170234],
                        'Fixed_Bond_Freq_Alignments': [0.010483410822070865]},
                        '28': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.1920321332950428],
                        'Fixed_Bond_Freq_Alignments': [0.009435523245986956]},
                        '26': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.162791425658376],
                        'Fixed_Bond_Freq_Alignments': [0.02338692106152805]},
                        '38': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.2099540903945893],
                        'Fixed_Bond_Freq_Alignments': [0.02357475310063674]},
                        '41': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.110859846141294],
                        'Fixed_Bond_Freq_Alignments': [0.020166313304517784]},
                        '23': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.1100793551612895],
                        'Fixed_Bond_Freq_Alignments': [0.019922582795366517]}},
            "TS8": {'7': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.2413903233174124],
                        'Fixed_Bond_Freq_Alignments': [0.0016274151505202283]},
                        '17': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3861293664677008],
                        'Fixed_Bond_Freq_Alignments': [0.004615807093614022]},
                        '8': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3619785979012422],
                        'Fixed_Bond_Freq_Alignments': [0.00659421851244933]},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3541093874644805],
                        'Fixed_Bond_Freq_Alignments': [0.003523273406869469]}},
            "TS9": {'29': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.4457658321498816],
                        'Fixed_Bond_Freq_Alignments': [0.005793905908329171, 0.006511039351622696]},
                        '42': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.3979836193349982],
                        'Fixed_Bond_Freq_Alignments': [0.021466773334758122, 0.004144020905301214]},
                        '24': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.4093000394047364],
                        'Fixed_Bond_Freq_Alignments': [0.016674241832334645, 0.002737764448153519]},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.417803754604817],
                        'Fixed_Bond_Freq_Alignments': [0.0014904488997673146, 0.004334957824155862]}},
            "TS10": {'34': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.1003523391002172],
                        'Fixed_Bond_Freq_Alignments': [0.015214551479349553,
                        0.007144680251621327,
                        0.00019156917662438433]},
                        '27': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.0895299597682113],
                        'Fixed_Bond_Freq_Alignments': [0.004981383504414277,
                        0.010800196847219085,
                        0.0016168509017941961]},
                        '37': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.093051653872931],
                        'Fixed_Bond_Freq_Alignments': [0.005421070978831363,
                        0.01261753473702085,
                        0.006495259232328167]},
                        '5': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.075817257820945],
                        'Fixed_Bond_Freq_Alignments': [0.0009532723178593844,
                        0.002215275128005234,
                        0.0011100538790219591]},
                        '25': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [2.097675117312388],
                        'Fixed_Bond_Freq_Alignments': [0.006491773517352466,
                        0.004713902604607065,
                        0.020438385363716657]}},
            "TS11": {'4': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': True,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.417791028694695],
                        'Fixed_Bond_Freq_Alignments': [0.0066097396560676445, 0.007203613136941064]},
                        '12': {'TS_direct_Validation': True,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': True,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.1939649004077477],
                        'Fixed_Bond_Freq_Alignments': [0.009526620539268362, 0.006573768258952263]},
                        '13': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': [0.004815406006209853, 0.005538113716028893]}},
            "TS12": {'21': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [0.9811213227200932],
                        'Fixed_Bond_Freq_Alignments': [0.023278564959236525,
                        0.0067492146705570855,
                        0.006323116692603631,
                        0.07346921280295021]},
                        '31': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': False,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': False,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': []},
                        '30': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': False,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': True,
                        'Struct Validation': False,
                        'Reaction_Bond_Freq_Alignments': [],
                        'Fixed_Bond_Freq_Alignments': []},
                        '15': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [0.9678409433232904],
                        'Fixed_Bond_Freq_Alignments': [0.006783761674584638,
                        0.02064869967640026,
                        0.006548153460631201,
                        0.07113170655055934]},
                        '25': {'TS_direct_Validation': False,
                        'IRC_Validation': False,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': True,
                        'Short_IRC': True,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [0.004200026370585516],
                        'Fixed_Bond_Freq_Alignments': [0.00011329795236941775,
                        0.0020208078556483433,
                        0.0006511736175107141,
                        0.00023733157794192383]}},
            "TS13": {'9': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.7075747758868607],
                        'Fixed_Bond_Freq_Alignments': [0.0263945245464553,
                        0.014471118933792236,
                        0.004697753638410552,
                        0.007292518995883311]},
                        '11': {'TS_direct_Validation': True,
                        'IRC_Validation': True,
                        'One_Endpoint_Valid': True,
                        'IRC_Endpoints_Match': False,
                        'Short_IRC': False,
                        'Struct Validation': True,
                        'Reaction_Bond_Freq_Alignments': [1.7333306982874477],
                        'Fixed_Bond_Freq_Alignments': [0.012347070632397511,
                        0.0055180657935720735,
                        0.007841807455232858,
                        0.01785043964455666]}}
        }
        
        TS_validity = {
            "TS0": {'7': False, '4': True, '12': False},
            "TS1": {'16': False, '15': False},
            "TS2": {'32': True, '11': True, '43': True, '30': True, '24': True},
            "TS3": {'7': True, '17': True, '8': True, '21': True, '15': True},
            "TS4": {'42': False, '43': False, '3': True, '25': True},
            "TS5": {'72': True, '15': True},
            "TS6": {'26': True, '43': True, '24': True, '15': True},
            "TS7": {'35': True, '28': True, '26': True, '38': True, '41': True, '23': True},
            "TS8": {'7': True, '17': True, '8': True, '15': True},
            "TS9": {'29': True, '42': True, '24': True, '15': True},
            "TS10": {'34': True, '27': True, '37': True, '5': True, '25': True},
            "TS11": {'4': False, '12': False, '13': False},
            "TS12": {'21': True, '31': False, '30': False, '15': True, '25': False},
            "TS13": {'9': True, '11': True},
        }
        
        for ts in TS_validity.keys():
            valid_dict,valid_info = validate_TS_configs(os.path.join(path,ts),sites,site_adjacency,nslab)
            self.assertEqual(valid_dict,TS_validity[ts])
            for ind in TS_validity_info[ts]:
                for k in TS_validity_info[ts][ind].keys():
                    if "Bond_Freq_Alignments" in k:
                        benchmark = sorted(TS_validity_info[ts][ind][k])
                        calculated = sorted(valid_info[ind][k])
                        for i in range(len(benchmark)):
                            self.assertAlmostEqual(benchmark[i],calculated[i])
                    else:
                        self.assertEqual(TS_validity_info[ts][ind][k],valid_info[ind][k])

if __name__ == '__main__':
    unittest.main()